# Project information
site_name: rootbox

nav:
    - Home: index.md
    - Getting Started:
        - Installation: getting-started/installation.md
    - References: references.md
theme:
    name: material
    language: en
    palette:
        primary: 'blue'
        accent: 'green'

copyright:  Copyright © Contributors to the RootBox project

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_get"
